apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.svcname }}
  name: {{ .Values.metadata.svcname }}
spec:
  ports:
  - name: {{ .Values.metadata.appname }}port
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: {{ .Values.metadata.appname }}
  type: NodePort
status:
  loadBalancer: {}